### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by artBoffin** [xem/webgl-guide#1]
This is a great guide (been following from here https://xem.github.io/articles/webgl-guide.html)
I notice that a license file is missing, are you intending to add it at some point?
If the license is permissive, it would be a great resource to build from for teaching creative coding and extending new works from.

(similarly having a clear license for https://github.com/xem/MiniShadertoy would be great since it could be useful to build & test examples from)

Thanks!

**Comment by xem** [comment]
Hello,
Thanks a lot for getting in touch and enjoying my content!
I added CC0 license to both repos :)
Be aware that my webgl guide "part 1" (the one you read) is not finished yet, I'm adding some extra tricks and will be announce it shortly on my Twitter (@maximeeuziere, I'm following you there and on instagram, nice content! 👍 )
I'm also looking for proofreaders, so if you find errors or things that are not well explained in my guide, I'd be happy to hear about them and fix them.
Cheers,
Max

**Comment by artBoffin** [comment]
Nice, it's quite generous to share all this knowledge.
If you have some free time on your hands, I would encourage you to add licenses to your other repositories. Gives people the green light to do cool stuff with them.
Thanks for the kind words! Looking forward to part 2.

**Comment by xem** [comment]
I wish Github repos were CC0 by default :(
But I rarely have licence requests like these, so I'll add licence files when someone demands it.
You can consider all my work CC0 by default, and feel free to ask licenses on any other repo(s).
I'd love to see what you do from these!

**Comment by artBoffin** [comment]
Great, thanks for the clarification!
Closing the issue.
